### ISSUE TITLE
Cannot use ContainerEngine as a shared static container

### ISSUE THREAD

**Issue by npepinpe** [camunda-community-hub/zeebe-test-container#318]
**Describe the bug**

It is not possible to share and reuse the same `ContainerEngine` instance for multiple tests at the moment, as we close the engine between each tests. This means it's only usable with a single test.

**To Reproduce**

```java
@Testcontainers
final class MyTest {
  @Container
  private static final ContainerEngine ENGINE =
      ContainerEngine.builder()
          .withIdlePeriod(Duration.ofSeconds(2))
          .build();

  @Test
  void shouldAssertFoo() {
    assertThat(BpmnAssert.getRecordStream().deploymentRecords()).hasSize(3);
  }

  @Test
  void shouldAssertBar() {
    assertThat(BpmnAssert.getRecordStream().deploymentRecords()).hasSize(3);
  }
}
```

**Expected behavior**

Instances `ContainerEngine` can be used with the built-in Testcontainers extension like any other container.

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue.

<details>
<summary>Full Stacktrace</summary>
<pre>
java.lang.IllegalStateException: stream has already been operated upon or closed

	at java.base/java.util.stream.AbstractPipeline.spliterator(AbstractPipeline.java:346)
	at java.base/java.util.stream.ReferencePipeline.iterator(ReferencePipeline.java:143)
	at org.assertj.core.presentation.StandardRepresentation.format(StandardRepresentation.java:603)
	at org.assertj.core.presentation.StandardRepresentation.singleLineFormat(StandardRepresentation.java:544)
	at org.assertj.core.presentation.StandardRepresentation.smartFormat(StandardRepresentation.java:558)
	at org.assertj.core.presentation.StandardRepresentation.toStringOf(StandardRepresentation.java:246)
	at org.assertj.core.presentation.CompositeRepresentation.toStringOf(CompositeRepresentation.java:40)
	at org.assertj.core.error.MessageFormatter.asText(MessageFormatter.java:78)
	at org.assertj.core.error.MessageFormatter.format(MessageFormatter.java:69)
	at org.assertj.core.error.MessageFormatter.format(MessageFormatter.java:62)
	at org.assertj.core.error.BasicErrorMessageFactory.create(BasicErrorMessageFactory.java:107)
	at org.assertj.core.internal.Failures.assertionErrorMessage(Failures.java:144)
	at org.assertj.core.internal.Failures.failure(Failures.java:125)
	at org.assertj.core.internal.Iterables.assertAllSatisfy(Iterables.java:1162)
	at org.assertj.core.api.AbstractIterableAssert.internalAllSatisfy(AbstractIterableAssert.java:3735)
	at org.assertj.core.api.AbstractIterableAssert.allSatisfy(AbstractIterableAssert.java:3731)
</pre>
</details>

**Comment by npepinpe** [comment]
False positive, this is an issue with zeebe-process-test.
